[2021-05-07 05:35:31,929] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t1 2021-05-07T05:35:30.402764+00:00 [queued]>
[2021-05-07 05:35:32,022] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t1 2021-05-07T05:35:30.402764+00:00 [queued]>
[2021-05-07 05:35:32,025] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 05:35:32,029] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-07 05:35:32,031] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 05:35:32,071] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): t1> on 2021-05-07T05:35:30.402764+00:00
[2021-05-07 05:35:32,088] {standard_task_runner.py:52} INFO - Started process 66 to run task
[2021-05-07 05:35:32,110] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'helloworld_dag', 't1', '2021-05-07T05:35:30.402764+00:00', '--job-id', '109', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/helloworld.py', '--cfg-path', '/tmp/tmp9oqlf6ql', '--error-file', '/tmp/tmpf0f57qy8']
[2021-05-07 05:35:32,115] {standard_task_runner.py:77} INFO - Job 109: Subtask t1
[2021-05-07 05:35:32,335] {logging_mixin.py:104} INFO - Running <TaskInstance: helloworld_dag.t1 2021-05-07T05:35:30.402764+00:00 [running]> on host 2900f64db589
[2021-05-07 05:35:32,472] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=helloworld_dag
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2021-05-07T05:35:30.402764+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-07T05:35:30.402764+00:00
[2021-05-07 05:35:32,476] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-07 05:35:32,481] {bash.py:158} INFO - Running command: echo hello && exit 1
[2021-05-07 05:35:32,510] {bash.py:169} INFO - Output:
[2021-05-07 05:35:32,514] {bash.py:173} INFO - hello
[2021-05-07 05:35:32,518] {bash.py:177} INFO - Command exited with return code 1
[2021-05-07 05:35:32,561] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-07 05:35:32,572] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=helloworld_dag, task_id=t1, execution_date=20210507T053530, start_date=20210507T053531, end_date=20210507T053532
[2021-05-07 05:35:32,654] {local_task_job.py:146} INFO - Task exited with return code 1
