[2021-05-07 05:34:18,545] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t1 2021-05-07T05:34:15.846675+00:00 [queued]>
[2021-05-07 05:34:18,620] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t1 2021-05-07T05:34:15.846675+00:00 [queued]>
[2021-05-07 05:34:18,624] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 05:34:18,628] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-07 05:34:18,632] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 05:34:18,687] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): t1> on 2021-05-07T05:34:15.846675+00:00
[2021-05-07 05:34:18,705] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2021-05-07 05:34:18,763] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'helloworld_dag', 't1', '2021-05-07T05:34:15.846675+00:00', '--job-id', '108', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/helloworld.py', '--cfg-path', '/tmp/tmpb9mfjcn9', '--error-file', '/tmp/tmpdkzof9xf']
[2021-05-07 05:34:18,768] {standard_task_runner.py:77} INFO - Job 108: Subtask t1
[2021-05-07 05:34:19,027] {logging_mixin.py:104} INFO - Running <TaskInstance: helloworld_dag.t1 2021-05-07T05:34:15.846675+00:00 [running]> on host 2900f64db589
[2021-05-07 05:34:19,195] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=helloworld_dag
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2021-05-07T05:34:15.846675+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-07T05:34:15.846675+00:00
[2021-05-07 05:34:19,201] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-07 05:34:19,207] {bash.py:158} INFO - Running command: echo hello && exit 1
[2021-05-07 05:34:19,244] {bash.py:169} INFO - Output:
[2021-05-07 05:34:19,251] {bash.py:173} INFO - hello
[2021-05-07 05:34:19,256] {bash.py:177} INFO - Command exited with return code 1
[2021-05-07 05:34:19,314] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-07 05:34:19,328] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=helloworld_dag, task_id=t1, execution_date=20210507T053415, start_date=20210507T053418, end_date=20210507T053419
[2021-05-07 05:34:19,449] {local_task_job.py:146} INFO - Task exited with return code 1
