[2021-05-07 05:11:33,858] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t1 2021-05-07T05:11:26.478413+00:00 [queued]>
[2021-05-07 05:11:34,237] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: helloworld_dag.t1 2021-05-07T05:11:26.478413+00:00 [queued]>
[2021-05-07 05:11:34,285] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 05:11:34,304] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2021-05-07 05:11:34,327] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-07 05:11:34,526] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): t1> on 2021-05-07T05:11:26.478413+00:00
[2021-05-07 05:11:34,621] {standard_task_runner.py:52} INFO - Started process 60 to run task
[2021-05-07 05:11:34,772] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'helloworld_dag', 't1', '2021-05-07T05:11:26.478413+00:00', '--job-id', '107', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/helloworld.py', '--cfg-path', '/tmp/tmpldgpvja9', '--error-file', '/tmp/tmp1_akt_4s']
[2021-05-07 05:11:34,794] {standard_task_runner.py:77} INFO - Job 107: Subtask t1
[2021-05-07 05:11:35,861] {logging_mixin.py:104} INFO - Running <TaskInstance: helloworld_dag.t1 2021-05-07T05:11:26.478413+00:00 [running]> on host 2900f64db589
[2021-05-07 05:11:36,938] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=helloworld_dag
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2021-05-07T05:11:26.478413+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-07T05:11:26.478413+00:00
[2021-05-07 05:11:36,959] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-07 05:11:37,000] {bash.py:158} INFO - Running command: echo hello && exit 1
[2021-05-07 05:11:37,138] {bash.py:169} INFO - Output:
[2021-05-07 05:11:37,177] {bash.py:173} INFO - hello
[2021-05-07 05:11:37,198] {bash.py:177} INFO - Command exited with return code 1
[2021-05-07 05:11:37,492] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-07 05:11:37,555] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=helloworld_dag, task_id=t1, execution_date=20210507T051126, start_date=20210507T051133, end_date=20210507T051137
[2021-05-07 05:11:38,245] {local_task_job.py:146} INFO - Task exited with return code 1
